### ISSUE TITLE
Update and simplify Python packaging

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/assesspy#11]
We currently use `setup.py`, `requirements.txt`, and a few other files to setup the package infrastructure for assesspy. Recent Python packages have moved toward consolidating their metadata, dependencies, etc in a `pyproject.toml` file. Here is an example package: https://github.com/r5py/r5py. We should consider moving to this format in order to simplify package building and management.

The downside of this is likely reduced compatibility with prior version of Python. The upside is reduced complexity + the ability to define build-only dependencies. If we decide to implement this issue, we should make `numpy` the sole dependencies of this package.

**Comment by wrridgeway** [comment]
we should also take this opportunity to start using pyright

**Comment by dfsnow** [comment]
Also giving this to @wagnerlmichael as a backburner project.
