### ISSUE TITLE
Add Gini index to AssessPy functions

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/assesspy#9]
This issue is a clone of https://github.com/ccao-data/assessr/issues/3. It is intended to maintain parity between the two packages.

> Recent literature from the IAAO and others has suggested using a Gini-like index for measuring vertical equity in property assessments. We should add such a measurement to this package and the [ccao](ccao-data/ccao] package, then add it to our existing batch of output statistics.
> 
> See https://researchexchange.iaao.org/jptaa/vol17/iss2/2/ and https://www.sciencedirect.com/science/article/abs/pii/S1051137723000372. 

## Python package checklist

- [x] Add new Gini function with `assesspy/formulas.py`
- [ ] Make sure your code updates meet styling and linting requirements (black + pyright)
- [ ] Use [reStructuredText Markup](https://devguide.python.org/documentation/markup/#) for documentation and build  documentation updates by running sphinx locally.
- [ ] Add unit tests, copying the existing tests for `cod()`
- [x] Run unit tests using `tox`
- [ ] Make pull request
- [ ] Cut new release version in GitHub

**Comment by wrridgeway** [comment]
Added a tiny bit about documentation, good otherwise.

**Comment by wrridgeway** [comment]
@Damonamajor you can ignore pyright since it hasn't been run on the repo yet and will throw errors for stuff you're not working on. I'll run it myself once you've merged your work.
